name: Run rust tests

on: [push]

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      
      - name: Setup tests
        run: |
          docker pull python:3.10-slim-buster

      - name: Test
        run: |
          cd planetwars-matchrunner
          cargo check
          cargo test --all